import type { Metadata } from 'next'
import {Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({
  weight:["300","400","500","600","700"],
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Work Place',
  description: 'Generated by create next app',
}

// #1a1c1e    #ffffff
// #252729     #f0f1f7

// #8d99b0
// #eff8ff
// #8d8e8f

// theme
// #b15a11
// #23b7e5
// #28bf94
// #e6533c
// #7f58d3

// #232323
// #908e93
// #8c9097

// sidebar
// #1a1c1e  #111c43  

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  )
}
